### ISSUE TITLE
[Discussion] Does dadb commands work on real device (not emulator)?

### ISSUE THREAD

**Issue by kiranpuppala** [mobile-dev-inc/dadb#10] opened 2022-01-25 04:54 UTC

**Comment by Leland-Takamine** [comment] 2022-01-25 18:37
This isn't supported yet but we plan to look into it in the future. We have an issue already open for this so closing this as a duplicate of #3

**Closed by Leland-Takamine** 2022-01-25 18:37 UTC

**Comment by Leland-Takamine** [comment] 2022-08-22 22:58
@kiranpuppala I've added documentation for connecting to a real device:

https://github.com/mobile-dev-inc/dadb#connecting-to-a-physical-device

Please let me know if this doesn't work for you use case! 🙏
